FROM condaforge/mambaforge:latest
LABEL org.opencontainers.image.source="https://github.com/LCR-BCCRC/lcr-scripts"
RUN mamba install --yes --name base \
        --channel conda-forge \
        "gsutil=4.53" \
    && mamba clean --all --yes
CMD ["/bin/bash"]
